---
title: "Tabelas de Contingência"
output: 
  bookdown::html_document2:
editor_options:
  chunk_output_type: console
---
# Tabelas de Contingência códigos

```{r setup,,message=F}
library('titanic')
library('tidyverse')
library('janitor')



```
#### Tabela 2x2


```{r,message=F,echo=F}
df=read_csv("ALUNO_PSICO2019.CSV")
df=df |> 
  filter(NU_ANO_INGRESSO==2019,TP_SITUACAO!="7") |> 
  mutate(NU_IDADE=as.factor(NU_IDADE)) |> 
  mutate_if(is.double,as.factor) |> 
  mutate(NU_IDADE=as.double(NU_IDADE)) |> 
  select(-X1,-IN_INGRESSO_CONVENIO_PECG,-IN_RESERVA_VAGAS,-IN_APOIO_SOCIAL,-CO_IES) |> 
  rename(Turno=TP_TURNO,Sexo=TP_SEXO,Idade=NU_IDADE,Deficiencia=IN_DEFICIENCIA,Nacionalidade=TP_NACIONALIDADE,
         Ingresso=NU_ANO_INGRESSO,Situaçao=TP_SITUACAO) |> 
  mutate(Sexo=fct_recode(Sexo,"Feminino"="1","Masculino"="2"),
         Turno=fct_recode(Turno,"Matutino"="1","Vespertino"="2","Noturno"="3","Integral"="4"),
         Nacionalidade=fct_recode(Nacionalidade,"Brasileira"="1","Exterior/Naturalizado"="2","Estrangeira"="3"),
         Situaçao=fct_collapse(Situaçao,Evadido=c("5","4"),Retido=c("2","3","6")))
 
  
# Só fiz recode das que queria dar uma pequena explorada em um primeiro momento

# ESSA TABELA AQUI TA USANDO O DF TITANIC
# Usando o pacote janitor
df |> 
    group_by(Sex,Survived) |>  
    summarise(n=n())   |>  
    spread(Survived, n)   
    rename(Surv_N=`0`,Surv_Y=`1`) |>  
    adorn_totals("row") |>  
    adorn_totals("col") |> 
    ungroup() 
   
```



```{r ead graphs,echo=FALSE}
GGally::ggpairs(df[,-1]) #Esse gráfico é overkill, mas serve pra dar um vislumbre das variáveis


#função para gerar os graficos de barras
g_t=function(df,v){
  df |> 
  ggplot(aes({{v}})) + 
  geom_bar(aes(fill={{v}}))+
  geom_text(stat='count',aes(label=..count..),vjust=-0.5)+
  theme_minimal()
  }



# Estudantes por sexo

g_t(df,Sexo)+
  labs(title ="Quantidade de Estudantes de Psicolocia por Sexo no Brasil em 2019",y="Quantidade")


g_t(df,Turno)+
  labs(title ="Quantidade de Estudantes de Psicolocia por Turno no Brasil em 2019",y="Quantidade")

df |> 
  ggplot(aes(x=Idade))+
  geom_freqpoly(bins=70)

df |> 
  ggplot(aes(Idade))+ 
  geom_boxplot()
  

```

```{r,tabelas de contingência 1v,echo=F}
#Função para gerar as tabelas de frequência para uma variavel
freq_table=function(df,v){
  df |> 
  count({{v}}) |> 
  mutate(prop=prop.table(n)) |>
  rename(Quantidade=n,Proporção=prop) |> 
  adorn_totals("row")
}
```


```{r ????????????}
df |> 
  count(as_factor(Idade)) |> 
  ggplot(aes(n,fct_reorder(`as_factor(Idade)`,n)))+
  geom_col()+
  labs(x="Quantidade de observações no DF", y="Idade")
```

```{r tabelas de contingência 2v}
freq_table2=function(df,v1,v2){
  df |> 
 group_by({{v1}},{{v2}}) |>  
    summarise(n=n())   |>  
    spread({{v2}}, n) |> 
    adorn_totals("row") |>  
    adorn_totals("col") |> 
    ungroup() 
}


 
```

















